### PR TITLE
Update snowfakery_recipe.md

### PR DESCRIPTION
**Pull request by allisonletts**
make the recipe template use checkboxes instead of bullets.

### CODE REVIEW

**Review by eehjunggnujhee — COMMENTED** [review]
@allisonletts I guess we can just push this. Do we want to review this in out next meeting? Is there a way we can formulate counter? Do you think we can link a project to a recipe related pull request so that we can review all the recipes from project archives. I have so many questions!

**Comment by allisonletts** [comment]
Happy to chat or find another time to meet. Not sure I understand about formulating counter.

**Comment by eehjunggnujhee** [comment]
@allisonletts  I was thinking of a mechanism to tag a pull request that is belongs to a creation of a new recipe. 
So we can count a number of new recipes based on hashtag. I was wondering we can add that instruction to the template.

**Comment by samanthashain** [comment]
@allisonletts @eehjunggnujhee do you need support to resolve this PR?  If yes, i can add to mtg agenda for tomorrow.

**Comment by eehjunggnujhee** [comment]
@samanthashain  @allisonletts 
This is a good template!. I was thinking we should bring this up in a group to see if there is anything to add.

**Comment by samanthashain** [comment]
@acrosman I don't know how to fix the branch conflict

**Pull request merged**
