### PR TITLE
Bug fix, and more RecTypes

### PR DESCRIPTION
**Pull request by programmer2coder**
Fixed bug. The -include was replaced. Create  ONE Opp of each of the normal recordtypes found in NPSP.

# Critical Changes
Fixed bug.

# Changes
The -include was replaced. Create  ONE Opp of each of the normal recordtypes found in NPSP.

# Issues Closed
Issue #92

### CODE REVIEW

**Review by jesslopez-sf — DISMISSED** [review]
Runs well and works as expected now, @programmer2coder ! [programmer2coder](https://github.com/programmer2coder) I'll go ahead and approve it. Do you know if we talked about adding some of the record type-specific fields back into the recipe at some point (i.e. for Membership Opportunities, populating the membership fields, for In-Kind Opportunities, populating the In-kind fields, etc.). Thanks and great job!

**Comment by programmer2coder** [comment]
Hey @jesslopez-sf I don't remember that specifically, but it was a few months ago so it could have been discussed...  While fixing this up I considered briefly that but didn't want to delay just getting a working version posted.  

I'm mostly familiar with Donations and Grants, so for the other types I would have to first use the UI to key in some realistic-looking sample data, consider which fields are generally used (though not required) for those recordtypes, decide which Snowfakery fake data types correspond to each field, then tweak the recipe for those fields.  Ha!  Hard to make fake data when you don't know what the real data looks like!

Also, although technically all the Opportunity Recordtypes that come with default NPSP, can be from org accounts, some are more commonly associated to households rather than orgs, but I didn't use household at all (because then i started thinking about Contacts ...)

**Comment by samanthashain** [comment]
@programmer2coder your skills are progressing SO much!  I am celebrating you!  Excited to see this in action on Thurs :)

**Comment by programmer2coder** [comment]
It's weighing in at just over 300 lines, lots of fields for 6 record types!  I put in a little bit of fancy stuff copied from other recipes to keep date values in some kind of order (membership end date AFTER membership start date, etc.)  I've pushed my latest commits up, and ready for review. @jesslopez-sf @samanthashain

**Review by eehjunggnujhee — APPROVED** [review]
@programmer2coder 
The recipe ran as described
Screen Shot 2022-05-15 at 6 11 40 PM

**Pull request merged**
